### ISSUE TITLE
Cobol compile is failing

### ISSUE THREAD

**Issue by edge05** [openmainframeproject/polycephaly#20]
05:38:44  ** Compiling Cobol for program HELLOWC and opts = 
05:38:47  Caught: com.ibm.dbb.build.BuildException: com.ibm.dbb.build.BuildException: BGZTK0016E An error occurred running BPXWDYN command 'alloc dd(TMP00001) shr'.
05:38:47  com.ibm.dbb.build.BuildException: com.ibm.dbb.build.BuildException: BGZTK0016E An error occurred running BPXWDYN command 'alloc dd(TMP00001) shr'.
05:38:47  	at com.ibm.dbb.build.MVSExec.doExecute(MVSExec.java:186)
05:38:47  	at com.ibm.dbb.build.AbstractExec.execute(AbstractExec.java:68)
05:38:47  	at com.ibm.dbb.build.IExecute$execute.call(Unknown Source)
05:38:47  	at com.zos.language.Compile.run(Compile.groovy:138)
05:38:47  	at com.zos.groovy.utilities.ZosAppBuild$_execute_closure3$_closure4.doCall(ZosAppBuild.groovy:180)
05:38:47  	at com.zos.groovy.utilities.ZosAppBuild$_execute_closure3.doCall(ZosAppBuild.groovy:153)
05:38:47  	at com.zos.groovy.utilities.ZosAppBuild.execute(ZosAppBuild.groovy:149)
05:38:47  	at com.zos.groovy.utilities.ZosAppBuild$execute.call(Unknown Source)
05:38:47  	at build.run(build.groovy:9)
05:38:47  Caused by: com.ibm.dbb.build.BuildException: BGZTK0016E An error occurred running BPXWDYN command 'alloc dd(TMP00001) shr'.
05:38:47  	at com.ibm.dbb.build.internal.Utils.bpxwdyn(Utils.java:77)
05:38:47  	at com.ibm.dbb.build.internal.JzosDDProcess.bpxwdyn(JzosDDProcess.java:58)
05:38:47  	at com.ibm.dbb.build.internal.AbstractDDProcess.alloc(AbstractDDProcess.java:82)
05:38:47  	at com.ibm.dbb.build.internal.AbstractDDProcess.alloc(AbstractDDProcess.java:52)
05:38:47  	at com.ibm.dbb.build.MVSExec.doExecute(MVSExec.java:81)
05:38:47  	... 8 more
05:38:47  Caused by: com.ibm.jzos.RcException: BPXWDYN failed; S99ERROR/S99INFO = 0x1708/0x2 RC=386400258 (0x17080002)
05:38:47  	at com.ibm.jzos.ZFile.bpxwdyn(ZFile.java:152)
05:38:47  	at com.ibm.dbb.build.internal.Utils.bpxwdyn(Utils.java:73)
05:38:47  	... 12 more
05:38:47  ** Build finished

**Comment by edge05** [comment]
Updated the UNIT parameters to the correct type
