### ISSUE TITLE
DBB build result failure

### ISSUE THREAD

**Issue by edge05** [openmainframeproject/polycephaly#24]
[2020-11-24T01:31:44.321Z]  Running MortgageApplication Collection
[2020-11-24T01:31:45.907Z] Caught: com.ibm.dbb.repository.ConnectionException: BGZTK0034E Attempting to create build result MortgageApplication:build.null at 'https://10.100.0.166:9443/dbb/rest/buildResult' resulted in error: HTTP/1.1 409 Conflict.
[2020-11-24T01:31:45.907Z] com.ibm.dbb.repository.ConnectionException: BGZTK0034E Attempting to create build result MortgageApplication:build.null at 'https://10.100.0.166:9443/dbb/rest/buildResult' resulted in error: HTTP/1.1 409 Conflict.
[2020-11-24T01:31:45.907Z] 	at com.ibm.dbb.repository.RepositoryClient.createBuildResult(RepositoryClient.java:885)
[2020-11-24T01:31:45.907Z] 	at com.ibm.dbb.repository.RepositoryClient$createBuildResult$0.call(Unknown Source)
[2020-11-24T01:31:45.907Z] 	at com.zos.groovy.utilities.Tools.initializeBuildArtifacts(Tools.groovy:356)
[2020-11-24T01:31:45.907Z] 	at com.zos.groovy.utilities.Tools$initializeBuildArtifacts$2.call(Unknown Source)
[2020-11-24T01:31:45.907Z] 	at com.zos.groovy.utilities.ZosAppBuild.execute(ZosAppBuild.groovy:73)
[2020-11-24T01:31:45.907Z] 	at com.zos.groovy.utilities.ZosAppBuild$execute.call(Unknown Source)
[2020-11-24T01:31:45.907Z] 	at build.run(build.groovy:9)
[2020-11-24T01:31:46.547Z] ** Build finished

**Comment by edge05** [comment]
Issue with DBB LInkScanner, removed the code for now.  Will look at it in future. Converting to enhancement
